name: rekloze
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+5

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.1.9
  http: ^1.4.0
  http_parser: ^4.1.2
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.7+1
  qr_flutter: ^4.0.0
  shared_preferences: ^2.5.3
  pdf: ^3.11.3
  printing: ^5.14.2
  intl: ^0.20.2
  screenshot: ^3.0.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  pdfx: ^2.9.2
  universal_html: ^2.2.4
  path_provider: ^2.1.5
  open_file: ^3.5.10
  share_plus: ^11.0.0
  image_picker: ^1.1.2
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  table_calendar: ^3.2.0
  flutter_local_notifications: ^19.4.0
  workmanager: ^0.7.0
  go_router: ^13.0.0
  permission_handler: ^11.0.1
#  background_fetch: ^1.2.2
#  device_info_plus: ^11.5.0
#  syncfusion_flutter_pdfviewer: ^30.1.37
#  url_launcher: ^6.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
